### ISSUE TITLE
Possible off-by-one error?

### ISSUE THREAD

**Issue by pzhaojohnson** [r2dt-bio/R2DT#121]
Seems like in the `generate_traveler_fasta` function (linked below) that there's a possible off-by-one error in generated dot-bracket structures when a sequence contains a leading 5' label.

https://github.com/RNAcentral/R2DT/blob/main/utils/rna2djsonschema.py

The first for loop would ignore the 5' label when generating the nucleotide sequence but the base-pair indices used in the second for loop to generate the dot-bracket structure are not updated to match the now shorter sequence.

**Comment by AntonPetrov** [comment]
@pzhaojohnson Thank you Philip! I will investigate for the next release and test in conjunction with the new RNAcanvas export functionality (I will add an RNAcanvas example json file to the `TestTemplateGeneration` test case).
