### ISSUE TITLE
Possible R2DT bug

### ISSUE THREAD

**Issue by ValWood** [r2dt-bio/R2DT#149]
Hi @AntonPetrov 

As you know we recently installed R2DT.

We found that quite a few ncRNAs unexpectedly got R2Dt predictions.

On inspection these features were actually in the ncRNAs on the opposite strands to known tRNAs

See
https://github.com/pombase/curation/issues/3715
for the examples.

I this the expected behaviour?

Best
Val

**Comment by ValWood** [comment]
Hang on; ignore, I think I know what is happening.

**Comment by ValWood** [comment]
Actually, something is a bit weird.

Here we have an antisense RNA
https://rnacentral.org/rna/URS000230DC2B/4896

and the tRNA on the opposite strand:
https://rnacentral.org/rna/URS0000005144/4896

both reporting the tRNA structure

**Comment by AntonPetrov** [comment]
Hi Val! 

I looked into `URS000230DC2B_4896` and it indeed gets a high scoring hit with Eukaryotic tRNA models from tRNAScan-SE:

```
Sequence           		tRNA	Bounds	tRNA	Anti	Intron Bounds	Inf	      
Name               	tRNA #	Begin	End	Type	Codon	Begin	End	Score	Note
--------           	------	-----	------	----	-----	-----	----	------	------
URS000230DC2B_4896 	1	593	520	Asn	GTT	0	0	81.5	
```

As you noted, this hit is on the reversed strand and it corresponds to the other RNA, `URS0000005144_4896`.

I agree that R2DT should not visualise hits from the reverse strand. I made a change and once it is merged and deployed, RNAcentral can recompute the PomBase diagrams using the new version. I expect the next R2DT release in ~2 weeks but it would take longer for RNAcentral to update their precomputed RNA 2D diagrams. 

Thank you for reporting this problem and please let me know if you notice anything else.
